usage:
	@echo "" 
	@echo "Makefile for Minix Demo Shell." 
	@echo "" 
	@echo "Usage:" 
	@echo " make all	# Compile everything"
	@echo " make clean	# Remove the compiled programs and temp output files"
	@echo ""

all:
	gcc demosh.c demosh.h main.c -o demosh
clean:
	rm -f demosh
